artifact_location: file:///D:/UsingSpace/Projects/Artificial Intelligent/ComputerVision/Detection
  System for Autonomous Driving Car/runs/mlflow/894693508680615329
creation_time: 1731349512082
experiment_id: '894693508680615329'
last_update_time: 1731349512082
lifecycle_stage: active
name: D:\UsingSpace\Projects\Artificial Intelligent\ComputerVision\Detection System
  for Autonomous Driving Car\Moving Object Detection\weights
