artifact_location: file:///D:/UsingSpace/Projects/Artificial Intelligent/ComputerVision/Detection
  System for Autonomous Driving Car/runs/mlflow/0
creation_time: 1731349511860
experiment_id: '0'
last_update_time: 1731349511860
lifecycle_stage: active
name: Default
