artifact_uri: file:///D:/UsingSpace/Projects/Artificial Intelligent/ComputerVision/Detection
  System for Autonomous Driving Car/runs/mlflow/894693508680615329/d5080741b36047a0acdcbf437e36e689/artifacts
end_time: 1731379427660
entry_point_name: ''
experiment_id: '894693508680615329'
lifecycle_stage: active
run_id: d5080741b36047a0acdcbf437e36e689
run_name: yolo_model14
run_uuid: d5080741b36047a0acdcbf437e36e689
source_name: ''
source_type: 4
source_version: ''
start_time: 1731349864104
status: 3
tags: []
user_id: Admins
